/* eslint-disable @typescript-eslint/no-var-requires */

// https://davibaltar.medium.com/documenta%C3%A7%C3%A3o-autom%C3%A1tica-de-apis-em-node-js-eb03041c643b

// cd <root>
// ls && rm swagger_output.json && node scripts/swagger.js

const swaggerAutogen = require("swagger-autogen")();

const doc = {
  info: {
    version: "1.0.0",
    title: "My API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:3000",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "User",
      description: "Endpoints",
    },
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: "apiKey",
      in: "header", // can be "header", "query" or "cookie"
      name: "X-API-KEY", // name of the header, query parameter or cookie
      description: "any description...",
    },
  },
  definitions: {
    Parents: {
      father: "Simon Doe",
      mother: "Marie Doe",
    },
    User: {
      name: "Jhon Doe",
      age: 29,
      parents: {
        $ref: "#/definitions/Parents",
      },
      diplomas: [
        {
          school: "XYZ University",
          year: 2020,
          completed: true,
          internship: {
            hours: 290,
            location: "XYZ Company",
          },
        },
      ],
    },
    AddUser: {
      $name: "Jhon Doe",
      $age: 29,
      about: "",
    },
    FindupUsers: {
      location: {
        street: {
          number: 4291,
          name: "Rua Santa Luzia ",
        },
        coordinates: {
          latitude: "-40.7384",
          longitude: "146.0172",
        },
        timezone: {
          offset: "-5:00",
          description: "Eastern Time (US & Canada), Bogota, Lima",
        },
        city: "Campo Largo",
        state: "Bahia",
        postcode: "11280",
      },
      gender: "female",
      name: {
        title: "Miss",
        first: "Ariovanda",
        last: "Aragão",
      },
      email: "ariovanda.aragao@example.com",
      login: {
        uuid: "b0d3e756-3c96-4c7c-97a0-bbdf4fc10568",
        username: "bluetiger236",
        password: "456456",
        salt: "xIm6fd1h",
        md5: "cb9a9fcb4e8ced83700551abdbf7e7c5",
        sha1: "a5864c30600b26d2bc5d9f603034ea42669d73da",
        sha256:
          "2b6761cdca64445c15d7b352ec30ba90eb75cca12db435cfb04f27be75b67bf9",
      },
      dob: {
        date: "1951-01-02T15:29:29.688Z",
        age: 69,
      },
      registered: {
        date: "2005-05-24T13:07:22.372Z",
        age: 15,
      },
      phone: "(53) 1924-4957",
      cell: "(90) 6530-2213",
      picture: {
        large: "https://randomuser.me/api/portraits/women/26.jpg",
        medium: "https://randomuser.me/api/portraits/med/women/26.jpg",
        thumbnail: "https://randomuser.me/api/portraits/thumb/women/26.jpg",
      },
      nat: "BR",
    },
  },
};

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./dist/endpoints.js"];

swaggerAutogen(outputFile, endpointsFiles, doc);
// swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
//   require("./dist/server.js"); // Your project's root file
// });
